# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\hi.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(901, 519)
        Dialog.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 50, 761, 471))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"font: italic 10pt \"Lucida Bright\";\n"
"")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(830, 50, 71, 41))
        self.label_2.setStyleSheet("background-color: rgb(40,64,73)")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(830, 90, 71, 41))
        self.label_3.setStyleSheet("background-color: rgb(255,255,255)")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(830, 170, 71, 41))
        self.label_4.setStyleSheet("background-color: rgb(255,255,255)")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(830, 130, 71, 41))
        self.label_5.setStyleSheet("background-color: rgb(40,64,73)")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(830, 250, 71, 41))
        self.label_6.setStyleSheet("background-color: rgb(255,255,255)")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(830, 210, 71, 41))
        self.label_7.setStyleSheet("background-color: rgb(40,64,73)")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(830, 330, 71, 41))
        self.label_8.setStyleSheet("background-color: rgb(255,255,255)")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(830, 290, 71, 41))
        self.label_9.setStyleSheet("background-color: rgb(40,64,73)")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(830, 410, 71, 41))
        self.label_10.setStyleSheet("background-color: rgb(255,255,255)")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(830, 370, 71, 41))
        self.label_11.setStyleSheet("background-color: rgb(40,64,73)")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(830, 490, 71, 41))
        self.label_12.setStyleSheet("background-color: rgb(255,255,255)")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(830, 450, 71, 41))
        self.label_13.setStyleSheet("background-color: rgb(40,64,73)")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(0, 90, 71, 41))
        self.label_14.setStyleSheet("background-color: rgb(255,255,255)")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(0, 170, 71, 41))
        self.label_15.setStyleSheet("background-color: rgb(255,255,255)")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(0, 130, 71, 41))
        self.label_16.setStyleSheet("background-color: rgb(40,64,73)")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(0, 290, 71, 41))
        self.label_17.setStyleSheet("background-color: rgb(40,64,73)")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(0, 450, 71, 41))
        self.label_18.setStyleSheet("background-color: rgb(40,64,73)")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(0, 410, 71, 41))
        self.label_19.setStyleSheet("background-color: rgb(255,255,255)")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(0, 250, 71, 41))
        self.label_20.setStyleSheet("background-color: rgb(255,255,255)")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(0, 50, 71, 41))
        self.label_21.setStyleSheet("background-color: rgb(40,64,73)")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(0, 210, 71, 41))
        self.label_22.setStyleSheet("background-color: rgb(40,64,73)")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(0, 370, 71, 41))
        self.label_23.setStyleSheet("background-color: rgb(40,64,73)")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(0, 330, 71, 41))
        self.label_24.setStyleSheet("background-color: rgb(255,255,255)")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(0, 490, 71, 41))
        self.label_25.setStyleSheet("background-color: rgb(255,255,255)")
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        ######################################################################
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(70, 50, 761, 471))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollArea.setWidget(self.label)
        ######################################################################
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


